#! Python3

# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four
# million, find the sum of the even-valued terms.

# Find all fibonacci numbers from 1 - 4 million, put them in memo


def F(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        return F(n-1)+F(n-2)
F(n)

# def fibo(n):
#     memo = {}
#     if n in memo:
#         return memo[n]
#     elif n <= 40000000:
#         f = 1
#     else:
#         f = fibo(n - 1) + fibo(n - 2)
#         memo[n] = f
#     return f
#
# fibo(0)



# For all even numbers in memo{}, add them together
